### LSColors
[".config/shell/lscolors.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.sh"

### Nano Syntax Highlighting
[".config/nano/syntax"]
    type = "archive"
    urls = ["https://github.com/scopatz/nanorc/archive/master.tar.gz"]
    refreshPeriod = "168h"
    stripComponents = 1
